/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import PropTypes from 'prop-types';
import React, { useEffect, useState } from 'react';
import { useGLTF } from '@react-three/drei';

function DomeDetail(props) {
  const { nodes, materials } = useGLTF('/models/dome_detail.glb');
  const { companies, job_applications, positions } = props;
  const [digits, setDigits] = useState('000000000000');

  useEffect(() => {
    setDigits(`${job_applications}${companies}${positions}`);
  }, [companies, job_applications, positions]);
  return (
    <group {...props} dispose={null}>
      <group position={[0, -148, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_1.geometry}
          material={materials.WHITE_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_2.geometry}
          material={materials.GREY_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_3.geometry}
          material={materials.GLASS_GLTF}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_4.geometry}
          material={materials.GREEN_1_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_5.geometry}
          material={materials.WATER_1_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_6.geometry}
          material={materials.BLACK_NUMBERS}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_7.geometry}
          material={materials.ROBO_GREY_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_8.geometry}
          material={materials.ROBO_WHITE_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_9.geometry}
          material={materials.ROBO_BLACK_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_10.geometry}
          material={materials.OGRADE_SIVE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_11.geometry}
          material={materials.LOGO_BRAND_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_12.geometry}
          material={materials.PANEL_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_13.geometry}
          material={materials['BLUE SCREEN_1']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_14.geometry}
          material={materials.EXIT_SIGN_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_15.geometry}
          material={materials.TOUCHSCREEN_BLUE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_16.geometry}
          material={materials['BLUE SCREEN_2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_17.geometry}
          material={materials.GOLDEN_BROWN_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_18.geometry}
          material={materials.KEYBOARD}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_19.geometry}
          material={materials.GREEN_3_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_20.geometry}
          material={materials.TOUCHSCREEN_RED}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_21.geometry}
          material={materials.PREGRADE_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_22.geometry}
          material={materials['BLUE SCREEN_3']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_23.geometry}
          material={materials.PORTAL_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_24.geometry}
          material={materials.GREEN_TREES}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_25.geometry}
          material={materials.SOFA_1_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_26.geometry}
          material={materials['BIG BANNER_DOME_PHY']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_27.geometry}
          material={materials.PANEL_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_28.geometry}
          material={materials.PANEL_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_29.geometry}
          material={materials.PANEL_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_30.geometry}
          material={materials.PANEL_6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_31.geometry}
          material={materials.PANEL_5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_32.geometry}
          material={materials.PANE_4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_33.geometry}
          material={materials.SHEMA}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_34.geometry}
          material={materials.FLOOR_MATERIAL_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_35.geometry}
          material={materials.FLOOR_MATERIAL_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_36.geometry}
          material={materials.BOOTH_MATERIAL_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_37.geometry}
          material={materials.PANEL_8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_38.geometry}
          material={materials.KINDLE_RED}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_39.geometry}
          material={materials.KINDLE_BLUE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_40.geometry}
          material={materials.A4_RED}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_41.geometry}
          material={materials.A4_BLUE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_42.geometry}
          material={materials.PANEL_7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOME_DETAIL_43.geometry}
          material={materials.PANEL_9}
        />
      </group>
      <group position={[0, -148, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ROBO_4_1.geometry}
          material={materials.ROBO_GREY_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ROBO_4_2.geometry}
          material={materials.ROBO_WHITE_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ROBO_4_3.geometry}
          material={materials.ROBO_BLACK_PHY}
        />
      </group>
      <group position={[0, -148, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ROBO_5_1.geometry}
          material={materials.ROBO_GREY_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ROBO_5_2.geometry}
          material={materials.ROBO_WHITE_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ROBO_5_3.geometry}
          material={materials.ROBO_BLACK_PHY}
        />
      </group>
      <group position={[0, -148, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ROBO_6_1.geometry}
          material={materials.ROBO_GREY_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ROBO_6_2.geometry}
          material={materials.ROBO_WHITE_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ROBO_6_3.geometry}
          material={materials.ROBO_BLACK_PHY}
        />
      </group>
      <group position={[0, -148, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ROBO_7_1.geometry}
          material={materials.ROBO_GREY_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ROBO_7_2.geometry}
          material={materials.ROBO_WHITE_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ROBO_7_3.geometry}
          material={materials.ROBO_BLACK_PHY}
        />
      </group>
      <group position={[0, -148, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LAPTOP_DOME_1.geometry}
          material={materials.ROBO_GREY_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LAPTOP_DOME_2.geometry}
          material={materials.ROBO_BLACK_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LAPTOP_DOME_3.geometry}
          material={materials.OGRADE_SIVE}
        />
      </group>
      <group position={[0, -148, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.POVRATAK_INFO_1.geometry}
          material={materials.ROBO_GREY_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.POVRATAK_INFO_2.geometry}
          material={materials.OGRADE_SIVE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.POVRATAK_INFO_3.geometry}
          material={materials.POVRATAK_INFO}
        />
      </group>
      <group position={[0, -148, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.POVRATAK_SAJAM_1.geometry}
          material={materials.ROBO_GREY_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.POVRATAK_SAJAM_2.geometry}
          material={materials.OGRADE_SIVE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.POVRATAK_SAJAM_3.geometry}
          material={materials.POVRATAK_SAJAM}
        />
      </group>
      <mesh //0
        castShadow
        receiveShadow
        geometry={nodes[`NU_${digits[0]}`].geometry}
        material={materials.BLACK_NUMBERS}
        position={[-668.637, 322.608, -1043.641]}
        rotation={[0, 0.593, 0]}
      />
      <mesh //1
        castShadow
        receiveShadow
        geometry={nodes[`NU_${digits[1]}`].geometry}
        material={materials.BLACK_NUMBERS}
        position={[-638.484, 322.61, -1063.212]}
        rotation={[0, 0.541, 0]}
      />
      <mesh //2
        castShadow
        receiveShadow
        geometry={nodes[`NU_${digits[2]}`].geometry}
        material={materials.BLACK_NUMBERS}
        position={[-605.151, 322.609, -1082.536]}
        rotation={[0, 0.506, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes[`NU_${digits[3]}`].geometry}
        material={materials.BLACK_NUMBERS}
        position={[-571.802, 322.607, -1098.7]}
        rotation={[0, 0.454, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes[`NU_${digits[4]}`].geometry}
        material={materials.BLACK_NUMBERS}
        position={[-56.439, 321.679, -1238.543]}
        rotation={[0, 0.07, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes[`NU_${digits[5]}`].geometry}
        material={materials.BLACK_NUMBERS}
        position={[-20.257, 321.626, -1240.23]}
        rotation={[0, 0.017, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes[`NU_${digits[6]}`].geometry}
        material={materials.BLACK_NUMBERS}
        position={[17.036, 321.578, -1240.166]}
        rotation={[0, -0.017, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes[`NU_8`].geometry}
        material={materials.BLACK_NUMBERS}
        position={[53.667, 321.619, -1237.676]}
        rotation={[0, -0.07, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes[`NU_${digits[8]}`].geometry}
        material={materials.BLACK_NUMBERS}
        position={[569.502, 322.608, -1100.877]}
        rotation={[0, -0.454, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes[`NU_${digits[9]}`].geometry}
        material={materials.BLACK_NUMBERS}
        position={[601.527, 322.61, -1084.549]}
        rotation={[0, -0.506, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes[`NU_${digits[10]}`].geometry}
        material={materials.BLACK_NUMBERS}
        position={[634.928, 322.609, -1065.345]}
        rotation={[0, -0.541, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes[`NU_${digits[11]}`].geometry}
        material={materials.BLACK_NUMBERS}
        position={[666.467, 322.607, -1044.9]}
        rotation={[0, -0.593, 0]}
      />
    </group>
  );
}

DomeDetail.propTypes = {
  companies: PropTypes.string,
  job_applications: PropTypes.string,
  positions: PropTypes.string,
};

DomeDetail.defaultProps = {
  companies: '0000',
  job_applications: '0000',
  positions: '0000',
};

export default DomeDetail;

useGLTF.preload('/models/dome_detail.glb');
