/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Landscape(props) {
  const { nodes, materials } = useGLTF('/models/landscape.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Landscape.geometry}
        material={materials.Frame}
      >
        <meshStandardMaterial
          roughness={1}
          metalness={0}
          opacity={1}
          color={'white'}
        ></meshStandardMaterial>
      </mesh>
    </group>
  );
}

useGLTF.preload('/models/landscape.glb');
