/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Path5(props) {
  const { nodes, materials } = useGLTF('/models/path5.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PATHS_5.geometry}
        material={materials.WHITE_PHY}
        position={[0, -200, 0]}
      />
    </group>
  );
}

useGLTF.preload('/models/path5.glb');
