/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, PerspectiveCamera } from '@react-three/drei';

export function Ring6SegmentLow(props) {
  const { nodes, materials } = useGLTF(`${process.env.NEXT_PUBLIC_ROOT}/models/ring6_segment_low.glb`);
  return (
    <group {...props} dispose={null}>
      <group position={[-318.199, 0, 0.001]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RING_6_MOD_LOW_1.geometry}
          material={materials.WHITE_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RING_6_MOD_LOW_2.geometry}
          material={materials.GREY_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RING_6_MOD_LOW_3.geometry}
          material={materials.GREEN_TREES}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RING_6_MOD_LOW_4.geometry}
          material={materials.GOLDEN_BROWN_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RING_6_MOD_LOW_5.geometry}
          material={materials.WATER_1_PHY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RING_6_MOD_LOW_6.geometry}
          material={materials.GREEN_2_PHY}
        />
      </group>
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        fov={79.278}
        position={[19582.412, 38752.43, 541.688]}
        rotation={[-2.218, 0, -1.524]}
      />
    </group>
  );
}

useGLTF.preload(`${process.env.NEXT_PUBLIC_ROOT}/models/ring6_segment_low.glb`);
