/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import DefaultMaterial from '../materials/DefaultMaterial';
import { useControls } from 'leva';
import { useLoader } from '@react-three/fiber';
import * as THREE from 'three';

export function Terrain(props) {
  const { nodes, materials } = useGLTF('/models/terrain_hills.glb');
  let opacity = 1;

  const color = '#aebe5c';

  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.2, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane006_1.geometry}
            material={materials.GREEN_1_PHY}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane006_2.geometry}
            material={materials.GREEN_3_PHY}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane006_3.geometry}
            material={materials.GREY_PHY}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane006_4.geometry}
            // material={materials.OGRADE_SIVE}
          >
            <meshStandardMaterial color={color} />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/terrain_hills.glb');
