/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import DefaultMaterial from '../materials/DefaultMaterial';
export function WaterRegion(props) {
  const { nodes, materials } = useGLTF('/models/waterRegion.glb');
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          // receiveShadow
          geometry={nodes.WaterRegion_1.geometry}
          material={materials.water}
        ></mesh>
        <mesh
          // castShadow
          receiveShadow
          geometry={nodes.WaterRegion_2.geometry}
        >
          <DefaultMaterial />
          {/* <meshStandardMaterial metalness={0.7} roughness={0.7} color={"white"}></meshStandardMaterial> */}
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload('/models/waterRegion.glb');
